version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend/Dockerfile
  proxy:
    build:
      context: .
      dockerfile: ./dockerfiles/proxy/Dockerfile
    volumes:
      - ./dockerfiles/proxy/conf.d:/etc/nginx/conf.d:ro
      - ./dockerfiles/shared/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
  letsencrypt:
    image: certbot/certbot
    volumes:
      - ./dockerfiles/shared/letsencrypt:/etc/letsencrypt
    command: certonly --standalone --domains jimmylin.org --email b00502013@gmail.com --agree-tos --no-eff-email --keep-until-expiring
