version: "3.9"

services:
  proxy:
    build:
      dockerfile: ./dockerfiles/proxy/Dockerfile
    volumes:
      - ./dockerfiles/proxy/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
  frontend:
    build:
      dockerfile: ./dockerfiles/frontend/Dockerfile
