version: "3.9"

services:
  proxy:
    build:
      dockerfile: ./dockerfiles/proxy.dockerfile
    ports:
      - 80:80
      - 443:443
  frontend:
    build:
      dockerfile: ./dockerfiles/frontend.dockerfile
    ports:
      - 3000:80
