version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend/Dockerfile
  proxy:
    # Use official Nginx base image to serve. The `alpine` version make the container smaller.
    # https://hub.docker.com/_/nginx
    image: nginx:alpine
    volumes:
      - ./dockerfiles/proxy/conf.d:/etc/nginx/conf.d:ro
      - ./dockerfiles/shared/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
  letsencrypt:
    # Use official certbot base image to serve.
    # https://hub.docker.com/r/certbot/certbot/
    image: certbot/certbot
    volumes:
      - ./dockerfiles/shared/letsencrypt:/etc/letsencrypt
    command: certonly --standalone --domains jimmylin.org --email b00502013@gmail.com --agree-tos --no-eff-email --keep-until-expiring
