version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: dockerfiles/proxy/Dockerfile
    ports:
      - 80:80
      - 443:443
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend/Dockerfile
    ports:
      - 3000:80
