version: "3.9"

services:
  certbot-letsencrypt:
    # Use official certbot base image to serve.
    # https://hub.docker.com/r/certbot/certbot/
    image: certbot/certbot
    # Prefix it with the project name for namespace.
    container_name: certbot-letsencrypt
    volumes:
      # Certbot put SSL certificate files in `/etc/letsencrypt`.
      # We want share this folder with our host & other containers.
      - certbot-letsencrypt:/etc/letsencrypt
    # We want certbot to run as `standalone` mode, which deal with `challange` with its own
    # built-in web server, instead of ours. And we pass all necessary arguments to run it
    # without console interactive. To learn more about these arguments:
    # https://certbot.eff.org/docs/using.html#certbot-command-line-options
    command:
      - certonly
      - --standalone
      - --domains
      - ${ROOT_DOMAIN}
      - --domains
      - ${WWW_DOMAIN}
      - --email
      - ${EMAIL}
      - --agree-tos
      - --no-eff-email
      - --renew-with-new-domains
    ports:
      - 80:80

volumes:
  certbot-letsencrypt:
    name: certbot-letsencrypt
