version: "3.9"

services:
  certbot-letsencrypt:
    # Use official certbot base image to serve.
    # https://hub.docker.com/r/certbot/certbot/
    image: certbot/certbot
    # Prefix it with the project name for namespace.
    # Suffix it with `init` to not confuse Docker with the normal one.
    container_name: j3y-certbot-letsencrypt-init
    volumes:
      # Certbot put SSL certificate files in `/etc/letsencrypt`.
      # We want share this folder with our host & other containers.
      - certbot-letsencrypt:/etc/letsencrypt
    # We want certbot to run as `standalone` mode, which deal with `challange` with its own
    # built-in web server, instead of ours. And we pass all necessary arguments to run it
    # without console interactive. To learn more about these arguments:
    # https://certbot.eff.org/docs/using.html#certbot-command-line-options
    ports:
      - 80:80
    command:
      - certonly
      - --standalone
      - --domains
      - ${MY_DOMAINS}
      - --email
      - ${MY_EMAIL}
      - --agree-tos
      - --no-eff-email
      - --keep-until-expiring

volumes:
  certbot-letsencrypt:
    # Prefix it with the project name for namespace.
    name: j3y-certbot-letsencrypt
