version: "3"

services:
  node-web:
    build:
      # Use repo's root as `context` because docker can't do COPY from parent directory.
      context: ../
      # Specify the location of `Dockerfile`, because it is not in the `context`.
      dockerfile: ./docker/web/dev.Dockerfile
    # Prefix it with the project name for namespace.
    # Suffix it with `dev` for not confuse Docker with the normal one.
    container_name: node-web-dev
    ports:
      # Expose port 3000 for Next.js.
      - 3000:3000
    volumes:
      # Code hot reload.
      - ..:/app
  
  postgres-db:
    # https://hub.docker.com/_/postgres
    # Use official PostgreSQL image to serve. The `alpine` version make the container smaller.
    image: postgres:alpine
    # Prefix it with the project name for namespace.
    container_name: j3y-postgres-db
    environment:
      # This variable will create the specified user with superuser power.
      POSTGRES_USER: admin
      # This environment variable sets the superuser password.
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
    # Prefix it with the project name for namespace.
    name: j3y-postgres-data
