version: "3.9"

services:
  node-web-dev:
    container_name: node-web-dev
    build:
      context: ../
      dockerfile: ./docker/services/node-web-dev/Dockerfile
    image: j3ydocker/j3y-node-web-dev:latest
    environment:
      # Used by Prisma to connect to DB.
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db-dev:5432/mydb
    ports:
      - 3000:3000
      
  postgres-db-dev:
    container_name: postgres-db-dev
    # https://hub.docker.com/_/postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: postgres-data
