version: "3.9"

services:
  node-web:
    build:
      context: ../
      dockerfile: ./docker/services/node-web/Dockerfile
    image: j3ydocker/j3y-node-web:latest
    environment:
      # Used by Prisma to connect to DB.
      DATABASE_URL: postgresql://admin:admin@postgres-db:5432/j3ydb
  nginx-proxy:
    # https://hub.docker.com/_/nginx
    image: nginx:alpine
    volumes:
      # Let Nginx output the result of executing `envsubst` to /etc/nginx/conf.d for serving.
      - ./nginx-proxy/volumes/templates:/etc/nginx/templates:ro
      # We want to share this folder with certbot to get SSL certificates files.
      - certbot-letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
      # Pass these environment variables as is. You can just declare them on your host,
      # but usually you want to do this with a `./.env` beside this file.
    environment:
      - SSL_CERTIFICATE_PATH
      - SSL_CERTIFICATE_KEY_PATH
      - CERBOT_HOST
      - WEB_HOST
      - WEB_PORT
  postgres-db:
    # https://hub.docker.com/_/postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    external: true
