version: "3.9"

services:
  postgres-db:
    # https://hub.docker.com/_/postgres
    # Use official PostgreSQL image to serve. The `alpine` version make the container smaller.
    image: postgres:alpine
    # Prefix it with the project name for namespace.
    container_name: j3y-postgres-db
    environment:
      # This variable will create the specified user with superuser power.
      POSTGRES_USER: admin
      # This environment variable sets the superuser password.
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
    # Prefix it with the project name for namespace.
    name: j3y-postgres-data
