name: CD on main push

on:
  push:
    branches:
    - main

jobs:
  ssh-deployment:
    name: SSH deployment
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config <<END
          Host dst
            HostName $HOST
            User $USERNAME
            IdentityFile ~/.ssh/key
            StrictHostKeyChecking no
          END
      - name: Run remote commands with SSH
        run: |
          ssh dst "git -C ~/repos/j3y pull"
          ssh dst "sudo docker-compose -f ~/repos/j3y/docker/prod.yml build"
          ssh dst "sudo systemctl stop j3y-web.service"
          ssh dst "sudo systemctl start j3y-web.service"
          ssh dst "sudo docker exec node-web npx prisma db push"
