name: Script with SSH

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Script with SSH
    runs-on: ubuntu-latest

    steps:
    - name: Script with SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/repos/j3y
          pwd
          ls -al

    - name: SSH script
      run: ssh -i ${{ secrets.KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} ls -al
