name: Remote scripts with SSH

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > ../private.key
        rm -f ~/.ssh/known_hosts
        ssh -i ../private.key jimub@jimmylin.org ls -al
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
