name: Remote scripts with SSH

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        echo $HOST
        echo $USERNAME
        echo $KEY
        echo $KEY > private
        ssh -i ./private $USERNAME@$HOST pwd
      shell: bash
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
