name: Remote scripts with SSH

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        echo 123
        echo $HOST
        echo 123 > myfile
        cat myfile
      shell: bash
      env:
        HOST: {{ secrets.HOST }}
