name: Remote scripts with SSH

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS_PROD" > ~/.ssh/known_hosts
        ssh -i ../private.key -tt $USERNAME@$SSH_KNOWN_HOSTS ls -al
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.HOST}}
        USERNAME: ${{secrets.USERNAME}}
