name: Remote scripts with SSH

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        echo $HOST
        echo $USERNAME
        echo $KEY
        echo $KEY > ~/.ssh/private.key
        ssh -i ~/.ssh/private.key -o UserKnownHostsFile=/github/home/.ssh/known_hosts -tt $USERNAME@$HOST "echo test > testfile1"
      shell: bash
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
